apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::599525540354:role/Simplebank-DeployRole
      username: github-user
      groups:
        - system:masters
    - rolearn: arn:aws:sts::599525540354:assumed-role/Simplebank-DeployRole/GitHubActions
      username: github-actions
      groups:
        - system:masters