apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::599525540354:role/Simplebank-DeployRole
      username: github-ci
      groups:
        - system:masters